apiVersion: v1
kind: ConfigMap
metadata:
  name: xpresspos-backend-config
  namespace: xpresspos
data:
  APP_NAME: XpressPOS
  APP_ENV: production
  APP_DEBUG: "false"
  APP_URL: https://api.xpresspos.id
  APP_BASE_PATH: /var/www/html
  APP_LOCALE: id
  APP_FALLBACK_LOCALE: id
  APP_TIMEZONE: Asia/Jakarta
  FRONTEND_URL: https://xpresspos.id
  ADMIN_URL: https://admin.xpresspos.id
  OWNER_DOMAIN: dashboard.xpresspos.id
  OWNER_URL: https://dashboard.xpresspos.id
  API_URL: https://api.xpresspos.id
  SESSION_DRIVER: cookie
  SESSION_LIFETIME: "120"
  SESSION_DOMAIN: .xpresspos.id
  SESSION_SECURE_COOKIE: "true"
  CACHE_DRIVER: file
  CACHE_PREFIX: xpresspos
  QUEUE_CONNECTION: sync
  BROADCAST_DRIVER: log
  FILESYSTEM_DISK: public
  SANCTUM_STATEFUL_DOMAINS: dashboard.xpresspos.id,admin.xpresspos.id,api.xpresspos.id
  CORS_ALLOWED_ORIGINS: https://api.xpresspos.id,https://xpresspos.id,https://user.xpresspos.id,https://admin.xpresspos.id,https://dashboard.xpresspos.id
  OCTANE_SERVER: roadrunner
  OCTANE_HTTPS: "true"
  OCTANE_CACHE_TABLE: octane_cache
  OCTANE_MAX_REQUESTS: "250"
  FILAMENT_APP_URL: https://admin.xpresspos.id
  FILAMENT_FILESYSTEM_DISK: public
  OWNER_APP_URL: https://dashboard.xpresspos.id
  COMPANY_PROFILE_URL: https://xpresspos.id
  BCRYPT_ROUNDS: "12"
  QUEUE_WORKER_TIMEOUT: "60"
  QUEUE_WORKER_SLEEP: "3"
  QUEUE_MAX_ATTEMPTS: "3"
